version: '3.7'
services:
  doc-file-service:
    profiles:
      - local-deployment
    container_name: doc-file-service
    image: hcmusdoc/doc-file-service:latest
    pull_policy: always
    restart: always
    ports:
      - "8081:8081"
    environment:
      DOC_MAIN_SERVICE_SPRING_PROFILES_ACTIVE: local-deployment
      DOC_FILE_SERVICE_SERVER_PORT: 8081
      DOC_FILE_SERVICE_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://host.docker.internal:8180/realms/doc-realm
      DOC_MAIN_SERVICE_DATASOURCE_URL: jdbc:postgresql://18.138.129.181:5432/alfresco
      ALFRESCO_DB_HOST: 18.138.129.181
      ALFRESCO_DATABASE: alfresco
      DOC_FILE_SERVICE_DATASOURCE_USERNAME: alfresco
      DOC_FILE_SERVICE_DATASOURCE_PASSWORD: alfresco
      DOC_FILE_SERVICE_BROKER_URL: tcp://18.138.129.181:61616
      DOC_FILE_SERVICE_ELASTICSEARCH_URIS: localhost:9200
      DOC_FILE_SERVICE_ELASTICSEARCH_USERNAME: elastic
      DOC_FILE_SERVICE_ELASTICSEARCH_PASSWORD: changeme
      DOC_FILE_SERVICE_RABBITMQ_HOST: 13.215.56.216
      DOC_FILE_SERVICE_RABBITMQ_PORT: 5672
      DOC_FILE_SERVICE_RABBITMQ_USERNAME: guest
      DOC_FILE_SERVICE_RABBITMQ_PASSWORD: guest
      DOC_FILE_SERVICE_RABBITMQ_TEMPLATE_EXCHANGE: doc.exchange
      DOC_FILE_SERVICE_RABBITMQ_TEMPLATE_ROUTING_KEY: doc.routingkey
      DOC_FILE_SERVICE_RABBITMQ_TEMPLATE_DEFAULT_RECEIVE_QUEUE: doc.doc-main-queue
      DOC_FILE_SERVICE_RABBITMQ_TEMPLATE_ATTACHMENT_QUEUE: doc.attachment-queue
      DOC_FILE_SERVICE_RABBITMQ_TEMPLATE_ATTACHMENT_ROUTING_KEY: doc.attachment-routing-key
      DOC_FILE_SERVICE_CONTENT_SERVICE_SECURITY_BASICAUTH_USERNAME: admin
      DOC_FILE_SERVICE_CONTENT_SERVICE_SECURITY_BASICAUTH_PASSWORD: admin
      DOC_FILE_SERVICE_CONTENT_SERVICE_URL: http://18.138.129.181:8181
      DOC_FILE_SERVICE_CONTENT_SERVICE_PATH: /alfresco/api/-default-/public/alfresco/versions/1
      DOC_FILE_SERVICE_CONTENT_SERVICE_SEARCH_PATH: /alfresco/api/-default-/public/search/versions/1
      DOC_FILE_SERVICE_ALFRESCO_DEFAULT_SITE_ID: hcmus-k19-doc
      DOC_FILE_SERVICE_ALFRESCO_DEFAULT_SITE_TITLE: HCMUS-K19-DOC
      DOC_FILE_SERVICE_ALFRESCO_DEFAULT_SITE_DESCRIPTION: HCMUS-K19-DOC
      DOC_FILE_SERVICE_ALFRESCO_DEFAULT_SITE_VISIBILITY: PRIVATE
      DOC_FILE_SERVICE_AWS_S3_ACCESS_KEY: AKIAS6FDZNZSRE6D6YZB
      DOC_FILE_SERVICE_AWS_S3_SECRET_KEY: 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
      DOC_FILE_SERVICE_AWS_S3_REGION: ap-southeast-1
      DOC_FILE_SERVICE_AWS_S3_BUCKET_NAME: prj-doc-attachments
      DOC_FILE_SERVICE_MINIO_URL: http://host.docker.internal:9000
      DOC_FILE_SERVICE_MINIO_ACCESS_KEY: BONlv1QPzcVqTwCYqo38
      DOC_FILE_SERVICE_MINIO_SECRET_KEY: 6QFApdfd8Py3kYT9mF04GpAXhSGsmDz5bU5uK2JL
      DOC_FILE_SERVICE_MINIO_BUCKET_NAME: prj-doc
      TZ: Asia/Ho_Chi_Minh

  minio:
    image: minio/minio
    container_name: doc-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Admin@123
    command: server --console-address ":9001" /data

volumes:
  minio_storage: { }
