spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8180/realms/doc-realm

  cloud:
    compatibility-verifier:
      enabled: false

  servlet:
    multipart:
      max-file-size: 3000KB # max file size for each request
      max-request-size: 3000KB # max request size for a multipart/form-data.

  datasource:
    url: jdbc:postgresql://localhost:5432/alfresco
    username: alfresco
    password: alfresco

  jms:
    cache:
      enabled: false

  activemq:
    broker-url: tcp://localhost:61616

  elasticsearch:
    uris: localhost:9200
    username: elastic
    password: changeme
    connection-timeout: 1s

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: doc.exchange
      routing-key: doc.routingkey
      default-receive-queue: doc.doc-main-queue
      attachment-queue: doc.attachment-queue
      attachment-routing-key: doc.attachment-routing-key

server:
  port: 8081

# HTTP Basic Authentication that will be used by the API
content:
  service:
    security:
      basicAuth:
        username: admin
        password: admin
    # Location of the server and API endpoints
    url: http://localhost:8181
    path: /alfresco/api/-default-/public/alfresco/versions/1
    search:
      path: /alfresco/api/-default-/public/search/versions/1

alfresco:
  default:
    siteId: hcmus-k19-doc
    siteTitle: HCMUS-K19-DOC
    siteDescription: HCMUS-K19-DOC
    siteVisibility: PRIVATE